[package]
name = "liner"
version = "0.1.0"
authors = ["MovingtoMars <definitelynotliam@gmail.com>"]

[lib]
name = "liner"

[[bin]]
name = "liner_test"

[dependencies]
termion = "1.0"
unicode-width = "0.1.*"
