[package]
name = "liner"
version = "0.4.5" # remember to update README
authors = ["MovingtoMars <definitelynotliam@gmail.com>"]
description = "A library offering readline-like functionality."
repository = "https://github.com/redox-os/liner"
homepage = "https://github.com/redox-os/liner"
keywords = ["readline", "line", "input", "editor", "completion"]
license = "MIT"
exclude = [
    "CONTRIBUTING.md",
    ".travis.yml",
]

[lib]
name = "liner"

[[bin]]
name = "liner_test"
path = "src/examples/main.rs"

[dependencies]
bytecount = "0.3.1"
termion = "1.4.0"
unicode-width = "0.1.*"

[dev-dependencies]
regex = "1.0.0"
