[package]
name = "liner"
version = "0.1.0"
authors = ["MovingtoMars <liam@bumblebee.net.nz>"]

[lib]
name = "liner"

[[bin]]
name = "liner_test"

[dependencies]

[dependencies.termion]
git = "https://github.com/Ticki/termion.git"
features = ["nightly"]
